var lexi = lexi || {};

/**
 * This hash holds optional configuration information for stamps.
 * When a lexi.Stamp object is created, these values will be used to
 * set properties on that object. If there is an opt_settings argument to the
 * lexi.Stamp constructor those settings will take precedence over these.
 *
 * Note: This file, unlike songs.js and sounds.js, etc. is manually created.
 */
lexi.stamps = {

  'mercury': {'width': 39, 'height': 39},
  'mercury2': {'width': 39, 'height': 39},
  'venus': {'width': 90, 'height': 90},
  'venus2': {'width': 90, 'height': 90},
  'earth': {'width': 91, 'height': 91},
  'earth3': {'width': 91, 'height': 91},
  'mars': {'width': 48, 'height': 48},
  'mars2': {'width': 48, 'height': 48},
  'jupiter': {'width': 968, 'height': 968},
  'jupiter2': {'width': 968, 'height': 968},
  'saturn': {'width': 1960, 'height': 1960,
             'hitWidth': 1000, 'hitHeight': 1000},
  'saturn3': {'width': 1960, 'height': 1960},
  'uranus': {'width': 364, 'height': 364},
  'uranus2': {'width': 364, 'height': 364},
  'neptune': {'width': 348, 'height': 348},
  'neptune2': {'width': 348, 'height': 348},
  'pluto': {'width': 16, 'height': 16},
  'pluto8': {'width': 16, 'height': 16},
  'sun': {'width': 300, 'height': 300},

  'kerstman': {'loops': 999},
  'sint': {'loops': 999},

  'kerstboom': {'hideInAssetsPanel': true},
  'kerstman': {'hideInAssetsPanel': true},
  'cadeau': {'hideInAssetsPanel': true},
  'pepernoot': {'hideInAssetsPanel': true},
  'sint': {'hideInAssetsPanel': true},

  'turkey5': {'loops': 999},

  'algeria': {'thumbBackground': '#808080'},
  'behrain': {'thumbBackground': '#808080'},
  'bulgaria': {'thumbBackground': '#808080'},
  'chile': {'thumbBackground': '#808080'},
  'cyprus': {'thumbBackground': '#808080'},
  'czechrepublic': {'thumbBackground': '#808080'},
  'estonia': {'thumbBackground': '#808080'},
  'finland': {'thumbBackground': '#808080'},
  'georgia': {'thumbBackground': '#808080'},
  'holysee': {'thumbBackground': '#808080'},
  'indonesia': {'thumbBackground': '#808080'},
  'japan': {'thumbBackground': '#808080'},
  'madagascar': {'thumbBackground': '#808080'},
  'malta': {'thumbBackground': '#808080'},
  'monaco': {'thumbBackground': '#808080'},
  'nepal': {'thumbBackground': '#808080'},
  'nigeria': {'thumbBackground': '#808080'},
  'oman': {'thumbBackground': '#808080'},
  'pakistan': {'thumbBackground': '#808080'},
  'panama': {'thumbBackground': '#808080'},
  'poland': {'thumbBackground': '#808080'},
  'qatar': {'thumbBackground': '#808080'},
  'russia': {'thumbBackground': '#808080'},
  'sanmarino': {'thumbBackground': '#808080'},
  'serbia': {'thumbBackground': '#808080'},
  'singapore': {'thumbBackground': '#808080'},
  'slovakia': {'thumbBackground': '#808080'},
  'slovenia': {'thumbBackground': '#808080'},
  'southkorea': {'thumbBackground': '#808080'},
  'tonga': {'thumbBackground': '#808080'},
  'uruguay': {'thumbBackground': '#808080'},
  'vaticancity': {'thumbBackground': '#808080'},

  'donut7': {'loops': 999},
  'donut8': {'loops': 999},
  'donut9': {'loops': 999},
  'donut10': {'loops': 999},
  'poisondonut': {'loops': 999},

  '24phonewhite': {'thumbBackground': '#808080'},
  'bagwhite': {'thumbBackground': '#808080'},
  'bakesale2': {'thumbBackground': '#808080'},
  'basket2white': {'thumbBackground': '#808080'},
  'box2white': {'thumbBackground': '#808080'},
  'cardswhite': {'thumbBackground': '#808080'},
  'cart2white': {'thumbBackground': '#808080'},
  'cart3white': {'thumbBackground': '#808080'},
  'cartwhite': {'thumbBackground': '#808080'},
  'gift5white': {'thumbBackground': '#808080'},
  'heart6white': {'thumbBackground': '#808080'},
  'lock2white': {'thumbBackground': '#808080'},
  'messagewhite': {'thumbBackground': '#808080'},
  'money2white': {'thumbBackground': '#808080'},
  'newwhite': {'thumbBackground': '#808080'},
  'ribbon2white': {'thumbBackground': '#808080'},
  'salewhite': {'thumbBackground': '#808080'},
  'shippingwhite': {'thumbBackground': '#808080'},
  'statswhite': {'thumbBackground': '#808080'},
  'truck14white': {'thumbBackground': '#808080'},
  'umbrella3white': {'thumbBackground': '#808080'},
  'zoomwhite': {'thumbBackground': '#808080'},

  'ninja7': {'loops':999, 'hitWidth': 100, 'hitHeight': 100},
  'donut6': {'loops': 999},
  'bird20': {'loops': 999},

  'desertcactus': {'width': 1536, 'height': 1024},
  'grayspires': {'width': 1536, 'height': 1024},
  'pinkcraters': {'width': 1536, 'height': 1024},
  'purplemountains': {'width': 1536, 'height': 1024},
  'reddishrocks': {'width': 1536, 'height': 1024},
  'yellowmountains': {'width': 1536, 'height': 1024},
  'bottletrees': {'width': 1536, 'height': 1024},
  'eyeballbushes': {'width': 1536, 'height': 1024},
  'grassyground': {'width': 1536, 'height': 1024},
  'greenmountains': {'width': 1536, 'height': 1024},
  'growythings': {'width': 1536, 'height': 1024},
  'mossyground': {'width': 1536, 'height': 1024},
  'orangecliffs': {'width': 1536, 'height': 1024},
  'purplecliffs': {'width': 1536, 'height': 1024},
  'purplecraters': {'width': 1536, 'height': 1024},
  'rootedground': {'width': 1536, 'height': 1024},
  'sandycliffs': {'width': 1536, 'height': 1024},
  'spiralbushes': {'width': 1536, 'height': 1024},

  'racoon': {'hideInAssetsPanel': true},
  'racoon3': {'hideInAssetsPanel': true},

  'falefel': {'hideInAssetsPanel': true},

  'egg7': {'hitWidth': 200, 'hitHeight':200},
  'firetruck2': {'loops': 999},

  'target6': {'hitWidth': 50, 'hitHeight': 50},

  'hoop': {'hitWidth': 150, 'hitHeight': 40},

  'electricstickmanvip': {'hideInAssetsPanel': true},
  'flamingstickmanvip': {'hideInAssetsPanel': true},
  'karategirlvip': {'hideInAssetsPanel': true},
  'pikachuvip': {'hideInAssetsPanel': true},
  'stickfigurevip': {'hideInAssetsPanel': true},
  'stickfigure2vip': {'hideInAssetsPanel': true},
  'stickghostvip': {'hideInAssetsPanel': true},
  'stickheavenvip': {'hideInAssetsPanel': true},
  'stickmustachemanvip': {'hideInAssetsPanel': true},
  'sticksnowmanvip': {'hideInAssetsPanel': true},

  'arrow8': {'thumbBackground': '#808080'},

  'ninjanickpants': {'hideInAssetsPanel': true},

  'flyswatter': {'hitWidth': 200, 'hitHeight': 120},

  'bugcoin': {'loops': 999, 'width': 100, 'height': 100},

  'bird11': {'loops': 999, 'width': 100, 'height': 100},
  'bird12': {'loops': 999, 'width': 100, 'height': 100},
  'bird13': {'loops': 999, 'width': 100, 'height': 100},
  'bird14': {'loops': 999, 'width': 100, 'height': 100},
  'bird15': {'loops': 999, 'width': 100, 'height': 100},
  'bird16': {'loops': 999, 'width': 100, 'height': 100},

  'spaceship3': {'hitWidth': 50, 'hitHeight': 50},

  'apple': {'width': 120, 'height': 120},
  'pencil': {'width': 120, 'height': 120},
  'rainbow': {'width': 120, 'height': 120},
  'cherry': {'width': 120, 'height': 120},
  'cherries': {'width': 120, 'height': 120},
  'b': {'width': 120, 'height': 120},
  'cloud': {'width': 120, 'height': 120},
  'hamburger': {'width': 120, 'height': 120},
  'burger': {'width': 120, 'height': 120},
  'girl': {'width': 120, 'height': 120},
  'boy': {'width': 120, 'height': 120},
  'girl2': {'width': 120, 'height': 120},
  'popsicle': {'width': 120, 'height': 120},
  'phone': {'width': 120, 'height': 120},
  'cellphone': {'width': 120, 'height': 120},
  'icecream': {'width': 120, 'height': 120},
  'icecreamcone': {'width': 120, 'height': 120},
  'cola': {'width': 120, 'height': 120},
  'soda': {'width': 120, 'height': 120},
  'notebook': {'width': 120, 'height': 120},
  'diary': {'width': 120, 'height': 120},
  'cookie': {'width': 120, 'height': 120},
  'watermelon': {'width': 120, 'height': 120},
  'melon': {'width': 120, 'height': 120},
  'drink': {'width': 120, 'height': 120},
  'glass': {'width': 120, 'height': 120},
  'tree': {'width': 120, 'height': 120},
  'flower': {'width': 120, 'height': 120},
  'bow': {'width': 120, 'height': 120},
  'bowtie': {'width': 120, 'height': 120},
  'tie': {'width': 120, 'height': 120},
  'bandaid': {'width': 120, 'height': 120},
  'bandage': {'width': 120, 'height': 120},
  'heart': {'width': 120, 'height': 120},
  'love': {'width': 120, 'height': 120},
  'ball': {'width': 120, 'height': 120},
  'soccer': {'width': 120, 'height': 120},
  'strawberry': {'width': 120, 'height': 120},
  'dogbowl': {'width': 120, 'height': 120},
  'mug': {'width': 120, 'height': 120},
  'cup': {'width': 120, 'height': 120},
  'coffee': {'width': 120, 'height': 120},
  'paintbrush': {'width': 120, 'height': 120},
  'brush': {'width': 120, 'height': 120},
  'carrot': {'width': 120, 'height': 120},
  'note': {'width': 120, 'height': 120},
  'musicalnote': {'width': 120, 'height': 120},
  'brush2': {'width': 120, 'height': 120},
  'paintbrush2': {'width': 120, 'height': 120},
  'hat': {'width': 120, 'height': 120},
  'partyhat': {'width': 120, 'height': 120},
  'disk': {'width': 120, 'height': 120},
  'floppy': {'width': 120, 'height': 120},
  'floppydisk': {'width': 120, 'height': 120},
  'star': {'width': 120, 'height': 120},
  'bone': {'width': 120, 'height': 120, 'hitHeight': 60, 'hitWidth': 120},
  'lime': {'width': 120, 'height': 120},
  'pen': {'width': 120, 'height': 120},
  'letter': {'width': 120, 'height': 120},
  'envelope': {'width': 120, 'height': 120},
  'shirt': {'width': 120, 'height': 120},
  'tshirt': {'width': 120, 'height': 120},
  'tv': {'width': 120, 'height': 120},
  'television': {'width': 120, 'height': 120},
  'bowl': {'width': 120, 'height': 120},
  'book': {'width': 120, 'height': 120},
  'shoe': {'width': 120, 'height': 120},
  'cupcake': {'width': 120, 'height': 120},
  'can': {'width': 120, 'height': 120},
  'usbdrive': {'width': 120, 'height': 120},
  'jumpdrive': {'width': 120, 'height': 120},
  'drive': {'width': 120, 'height': 120},
  'pear': {'width': 120, 'height': 120},
  'beachball': {'width': 120, 'height': 120},
  'popsicle2': {'width': 120, 'height': 120},
  'orange': {'width': 120, 'height': 120},
  'moon2': {'width': 120, 'height': 120},
  'asteroid': {'width': 120, 'height': 120},
  'nova': {'width': 120, 'height': 120},
  'explosion': {'width': 120, 'height': 120},
  'email': {'width': 120, 'height': 120},
  'share': {'width': 120, 'height': 120},

  'beccabotvip': {'hideInAssetsPanel': true},
  'bitsboxdrawingvip': {'hideInAssetsPanel': true},
  'carsonbotvip': {'hideInAssetsPanel': true},
  'finvip': {'hideInAssetsPanel': true},
  'machamponmountainvip': {'hideInAssetsPanel': true},
  'maildayvip': {'hideInAssetsPanel': true},
  'smileyheartvip': {'hideInAssetsPanel': true},
  'thumbsupvip': {'hideInAssetsPanel': true},
  'happypottervip': {'hideInAssetsPanel': true},


  'campgroundvip': {'hideInAssetsPanel': true},
  'catfacevip': {'hideInAssetsPanel': true},
  'chickenvip': {'hideInAssetsPanel': true},
  'codersuperherovip': {'hideInAssetsPanel': true},
  'colorsvip': {'hideInAssetsPanel': true},
  'destroyervip': {'hideInAssetsPanel': true},
  'dog4vip': {'hideInAssetsPanel': true},
  'drawafacevip': {'hideInAssetsPanel': true},
  'evelynvip': {'hideInAssetsPanel': true},
  'happyfacevip': {'hideInAssetsPanel': true},
  'jillianvip': {'hideInAssetsPanel': true},
  'kingoffishvip': {'hideInAssetsPanel': true},
  'letsgobitsboxvip': {'hideInAssetsPanel': true},
  'mermaidsvssharksvip': {'hideInAssetsPanel': true},
  'nofaceonelegwizzardvip': {'hideInAssetsPanel': true},
  'riuvip': {'hideInAssetsPanel': true},
  'stickmanvip': {'hideInAssetsPanel': true},
  'theflashvip': {'hideInAssetsPanel': true},
  'tocko1vip': {'hideInAssetsPanel': true},
  'trixievip': {'hideInAssetsPanel': true},
  'videogameredemptionvip': {'hideInAssetsPanel': true},
  'wentenvip': {'hideInAssetsPanel': true},
  'yourockvip': {'hideInAssetsPanel': true},

  'bunny4': {'width': 300, 'height': 300},
  'snowball2': {'width': 100, 'height': 100},
  'yeti2': {'width': 200, 'height': 200},
  'crab4': {'loops': 9999, 'hitWidth': 150, 'hitHeight': 150},
  'jellyfish3': {'loops': 9999, 'hitWidth': 250, 'hitHeight': 250},

  'trampoline2': {'hitHeight': 200, 'hitWidth': 300},

  'dogasusvip': {'hideInAssetsPanel': true},
  'lovingheartvip': {'hideInAssetsPanel': true},
  'dragon2vip': {'hideInAssetsPanel': true},
  'mermaidpaintingvip': {'hideInAssetsPanel': true},
  'griffonvip': {'hideInAssetsPanel': true},
  'pikminvip': {'hideInAssetsPanel': true},
  'ilovemathvip': {'hideInAssetsPanel': true},
  'poopvip': {'hideInAssetsPanel': true},
  'lovingcatvip': {'hideInAssetsPanel': true},
  'racetoinfinityvip': {'hideInAssetsPanel': true},
  'lovingheart2vip': {'hideInAssetsPanel': true},
  'rockeyvip': {'hideInAssetsPanel': true},
  'dantdmvip': {'hideInAssetsPanel': true},
  'dodo2': {'loops': 999},
  'rob': {'hitWidth': 10},
  'rob1': {'hitWidth': 10},
  'rob2': {'hitWidth': 10},
  'rob3': {'hitWidth': 10},
  'rob4': {'hitWidth': 10},
  'rob5': {'hitWidth': 10},
  'rob6': {'hitWidth': 10},
  

  'barbara': {'hideInAssetsPanel': true},
  'chris': {'hideInAssetsPanel': true},
  'daymond': {'hideInAssetsPanel': true},
  'kevin': {'hideInAssetsPanel': true},
  'lori': {'hideInAssetsPanel': true},
  'mark': {'hideInAssetsPanel': true},
  'robert': {'hideInAssetsPanel': true},         
     
  'toyboat': {'loops': 999},
  'toyboat2': {'loops': 999},

  'armyguy2vip': {'hideInAssetsPanel': true},
  'armyguyvip': {'hideInAssetsPanel': true},
  'dinosaurvip': {'hideInAssetsPanel': true},
  'dragonvip': {'hideInAssetsPanel': true},
  'jaguarvip': {'hideInAssetsPanel': true},
  'swordvip': {'hideInAssetsPanel': true},
  'chapman': {'hideInAssetsPanel': true},
  'ship4': {'width': 150, 'height': 150},

  'ballicon2': {'thumbBackground': '#808080'},
  'boneicon2': {'thumbBackground': '#808080'},
  'cloud5': {'thumbBackground': '#808080'},
  'cloud6': {'thumbBackground': '#808080'},
  'dogtailicon2': {'thumbBackground': '#808080'},
  'hydranticon2': {'thumbBackground': '#808080'},
  'moon4': {'thumbBackground': '#808080'},
  'skull7': {'thumbBackground': '#808080'},
  'snow': {'thumbBackground': '#808080'},
  'squirrelicon2': {'thumbBackground': '#808080'},
  'star7': {'thumbBackground': '#808080'},
  'star8': {'thumbBackground': '#808080'},
  'star14': {'thumbBackground': '#808080'},
  'sun6': {'thumbBackground': '#808080'},

  'alien11vip': {'hideInAssetsPanel': true},
  'cyborgvip': {'hideInAssetsPanel': true},
  'gecko2vip': {'hideInAssetsPanel': true},
  'goldenfinchvip': {'hideInAssetsPanel': true},
  'karatemouse2vip': {'hideInAssetsPanel': true},
  'rainbowblobvip': {'hideInAssetsPanel': true},
  'topsecretvip': {'hideInAssetsPanel': true},
  'babyvip': {'hideInAssetsPanel': true},
  'dog2vip': {'hideInAssetsPanel': true},
  'geckovip': {'hideInAssetsPanel': true},
  'hampstervip': {'hideInAssetsPanel': true},
  'karatemousevip': {'hideInAssetsPanel': true},
  'supergirls2vip': {'hideInAssetsPanel': true},
  'bffvip': {'hideInAssetsPanel': true},
  'dog3vip': {'hideInAssetsPanel': true},
  'ghostbustersvip': {'hideInAssetsPanel': true},
  'hikariandkeivip': {'hideInAssetsPanel': true},
  'kennedyvip': {'hideInAssetsPanel': true},
  'supergirls3vip': {'hideInAssetsPanel': true},
  'coolsunvip': {'hideInAssetsPanel': true},
  'dogvip': {'hideInAssetsPanel': true},
  'girlvip': {'hideInAssetsPanel': true},
  'housevip': {'hideInAssetsPanel': true},
  'palettevip': {'hideInAssetsPanel': true},
  'supergirlsvip': {'hideInAssetsPanel': true},

  'police2': {'loops': 999},
  'controller': {'hitWidth':620,'hitHeight':280},

  'plumber': {'hitWidth': 100, 'hitHeight': 50},
  'platform': {'hitWidth': 420, 'hitHeight': 150},
  'haircolor': {'hitHeight': 140},
  'cymbal': {'hitWidth': 280, 'hitHeight': 175},
  'hihat': {'hitWidth': 290, 'hitHeight': 130},
  'snare': {'hitWidth': 230, 'hitHeight': 190},
  'bird10': {'loops': 999, 'width': 100, 'height': 100 },
  'ninja': {'width': 200, 'height': 200},
  'cowbell': {'width': 200, 'height': 200, 'hitWidth': 500, 'hitHeight': 340},
  'dragon7': {'hitWidth': 150, 'hitHeight': 150, 'loops': 999},
  'atile': {'width': 100, 'height': 100},
  'btile': {'width': 100, 'height': 100},
  'ctile': {'width': 100, 'height': 100},
  'dtile': {'width': 100, 'height': 100},
  'etile': {'width': 100, 'height': 100},
  'ftile': {'width': 100, 'height': 100},
  'gtile': {'width': 100, 'height': 100},
  'htile': {'width': 100, 'height': 100},
  'itile': {'width': 100, 'height': 100},
  'jtile': {'width': 100, 'height': 100},
  'ktile': {'width': 100, 'height': 100},
  'ltile': {'width': 100, 'height': 100},
  'mtile': {'width': 100, 'height': 100},
  'ntile': {'width': 100, 'height': 100},
  'otile': {'width': 100, 'height': 100},
  'ptile': {'width': 100, 'height': 100},
  'qtile': {'width': 100, 'height': 100},
  'rtile': {'width': 100, 'height': 100},
  'stile': {'width': 100, 'height': 100},
  'ttile': {'width': 100, 'height': 100},
  'utile': {'width': 100, 'height': 100},
  'vtile': {'width': 100, 'height': 100},
  'wtile': {'width': 100, 'height': 100},
  'xtile': {'width': 100, 'height': 100},
  'ytile': {'width': 100, 'height': 100},
  'ztile': {'width': 100, 'height': 100},
  
  'bananas2': {'width': 75, 'height': 75},
  'crocodile': {'width': 200, 'height': 200},

  'hotdog5': {'width': 300, 'height': 300},
  'pie3': {'width': 200, 'height': 200},
  'soda2': {'width': 200, 'height': 200},

  'drone4': {'hitWidth':200, 'hitHeight':100},

  'cityblock3': {'hitWidth': 325, 'hitHeight': 450, 'width': 125, 'height': 125},
  'spintaxi2': {'hitWidth': 40, 'hitHeight': 40},
  'building5': {'hitWidth': 350, 'hitHeight': 175, 'width': 200, 'height': 200},
  'camper3': {'hitWidth': 150, 'hitHeight': 150, 'width': 100, 'height': 100},
  'train2': {'hitWidth': 500, 'hitHeight': 100},

  'cat6': {'width': 150, 'height': 150},
  'skeleton4': {'hitWidth': 200, 'hitHeight': 500},
  'skeleton5': {'hitWidth': 200, 'hitHeight': 500},
  'skeleton6': {'hitWidth': 200, 'hitHeight': 500},
  'zombie9': {'loops': 10},

  'mouth3': {'width': 250, 'height': 250, 'hitWidth': 200, 'hitHeight': 200},
  'monster4': {'width': 175, 'height': 175},
  'bed2': {'width': 200, 'height': 200},
  'sofa2': {'width': 200, 'height': 200},
  'planter2': {'width': 150, 'height': 150},
  'bed': {'width': 200, 'height': 200},
  'crib': {'width': 150, 'height': 150},
  'chair2': {'width': 150, 'height': 150},
  'sofa': {'width': 200, 'height': 200},
  'nightstand': {'width': 150, 'height': 150},
  'chair3': {'width': 150, 'height': 150},
  'bookshelf': {'width': 200, 'height': 200},
  'nightstand2': {'width': 150, 'height': 150},
  'chair4': {'width': 120, 'height': 120},
  'table': {'width': 175, 'height': 175},
  'cabinet': {'width': 150, 'height': 150},
  'planter': {'width': 150, 'height': 150},
  'chair5': {'width': 150, 'height': 150},
  'table2': {'width': 150, 'height': 150},
  'chair': {'width': 130, 'height': 130},
  'chair6': {'width': 120, 'height': 120},
  'tv3': {'width': 175, 'height': 175},

  'flare3': {'width': 50, 'height': 50},
  'kite3': {'width': 300, 'height': 300},
  'yoyo': {'width': 200, 'height': 200},
  'alien9': {'width': 200, 'height': 200},
  'eyeball2': {'width': 80, 'height': 80},
  'orange3': {'width': 200, 'height': 200},
  'brain3': {'width': 100, 'height': 100},
  'bubble2': {'width': 400, 'height': 400},
  'popcorn7': {'width': 200, 'height': 200},
  'hotdog3': {'width': 400, 'height': 400},
  'hotdog4': {'width': 500, 'height': 500},
  'rock10': {'width': 200, 'height': 200},
  'star6': {'width': 500, 'height': 500},
  'yarn': {'width': 100, 'height': 100},
  'kitty': {'width': 400, 'height': 400},

  'tiger4': {'width': 555, 'height': 555},
  'turtle2': {'width': 275, 'height': 275},
  'dog4': {'width': 330, 'height': 330},
  'shrimp': {'width': 200, 'height': 200},
  'pig3': {'width': 180, 'height': 180},
  'face2': {'height': 300, 'width': 300, 'hitWidth': 250, 'hitHeight': 400},
  'face3': {'height': 300, 'width': 300},
  'popcorn': {'height': 150, 'width': 150, 'hitWidth': 140, 'hitHeight': 300},
  'fish10': {'width': 100, 'height': 100, 'hitWidth': 250, 'hitHeight': 250},
  'jellyfish2': {'width': 100, 'height': 100, 'hitWidth': 350, 'hitHeight': 350},

  'zombie4': {'hitWidth':200, 'hitHeight':200, 'width':100, 'height':100},
  'truck11': {'hitWidth':500, 'hitHeight':200, 'width':200, 'height':200},
  'taxi': {'hitWidth':500, 'hitHeight':200, 'width':200, 'height':200},
  'ship3': {'hitWidth':879, 'hitHeight':200, 'width':300, 'height':300},
  'buttonup': {'width':60, 'height': 60},
  'buttondown': {'width':60, 'height': 60},
  'buttonleft': {'width':60, 'height': 60},
  'buttonright': {'width':60, 'height': 60},
  'zombie5': {'width':300, 'height': 300},

  'alienbee': {'width': 200, 'height': 200},
  'resizer': {'width': 300, 'height': 300, 'hitWidth': 500, 'hitHeight': 200},
  'cupcake3': {'width': 50, 'height': 50},
  'trex': {'width': 250, 'height': 250, 'hitWidth': 200, 'hitHeight': 200},
  'meteor1': {'width': 50, 'height': 50},
  'meteor2': {'width': 75, 'height': 75},
  'meteor3': {'width': 100, 'height': 100},
  'meteor4': {'width': 125, 'height': 125},
  'meteor5': {'width': 150, 'height': 150},
  'meteor6': {'width': 200, 'height': 200},

  'dig': {'width': 75, 'height': 75},
  'fist': {'width': 300, 'height': 300},
  'fly2': {'width': 50, 'height': 50},
  'spider2': {'width': 100, 'height': 100},
  'hero': {'width': 200, 'height': 200},
  'cloud4': {'width': 50, 'height': 50},
  'kitten3': {'width': 120, 'height': 120},
  'hero2': {'width': 350, 'height': 350, 'hitWidth': 200, 'hitHeight': 200},
  'flare2': {'width': 1400, 'height': 1400},
  'ball2': {'width': 100, 'height': 100, 'hitWidth': 300, 'hitHeight': 300},
  'elffire': {'width': 300, 'height': 300},
  'elfwood': {'width': 300, 'height': 300},
  'elfwater': {'width': 300, 'height': 300},
  'coinfire': {'width': 100, 'height': 100},
  'coinwood': {'width': 100, 'height': 100},
  'coinwater': {'width': 100, 'height': 100},
  'watersprite': {'width': 300, 'height': 300},
  'poop': {'hideInAssetsPanel': true},
  'poo': {'hideInAssetsPanel': true},
  'circle': {'width': 10, 'height': 10, 'thumbBackground': '#808080'},
  'drone2': {'width': 250, 'height': 250},
  'rocket6': {'width': 60, 'height': 60},
  'drone': {'width': 150, 'height': 150, 'hitWidth': 100, 'hitHeight': 50},
  'pad': {'width': 200, 'height': 200, 'hitWidth': 150, 'hitHeight': 50},
  'pillar': {'width': 100, 'height': 100},
  'car7': {'hitWidth': 200, 'hitHeight': 400},
  'cone3': {'hitWidth': 10, 'hitHeight': 100},
  'kat': {'hitWidth': 50, 'hitHeight': 50},
  'laser2': {'hitWidth': 350, 'hitHeight': 50},
  'flame': {'loops': 999},
  'server': {'hitWidth': 100, 'hitHeight': 100},
  'mag': {'hitWidth': 300, 'hitHeight': 300},
  'bot': {'width': 150, 'height': 150},
  'swipe': {'hitHeight': 10, 'hitWidth': 10},
  'bizguy': {'hitHeight': 60, 'hitWidth': 60},
  'bizguy2': {'hitHeight': 60, 'hitWidth': 60},
  'chain': {'hitHeight': 10, 'hitWidth': 10},
  'claw': {'hitHeight': 30, 'hitWidth': 30},
  'cyclist': {'hitHeight': 50, 'hitWidth': 50, 'thumbBackground': '#808080'},
  'saucer': {'hitHeight': 100, 'hitWidth': 100},
  'whitekey': {'hitWidth': 60, 'hitHeight': 350, 'thumbBackground': '#808080'},
  'whitekey2': {'hitWidth': 60, 'hitHeight': 350, 'thumbBackground': '#808080'},
  'pianoa': {'hitWidth': 74, 'hitHeight': 276, 'thumbBackground': '#808080'},
  'pianob': {'hitWidth': 74, 'hitHeight': 276, 'thumbBackground': '#808080'},
  'pianoc': {'hitWidth': 74, 'hitHeight': 276, 'thumbBackground': '#808080'},
  'pianod': {'hitWidth': 74, 'hitHeight': 276, 'thumbBackground': '#808080'},
  'pianoe': {'hitWidth': 74, 'hitHeight': 276, 'thumbBackground': '#808080'},
  'pianof': {'hitWidth': 74, 'hitHeight': 276, 'thumbBackground': '#808080'},
  'pianog': {'hitWidth': 74, 'hitHeight': 276, 'thumbBackground': '#808080'},
  'trampoline': {'hitHeight': 115, 'hitWidth': 354},
  'jumper': {'hitHeight': 200, 'hitWidth': 200},
  'jumper2': {'hitHeight': 200, 'hitWidth': 200},
  'boyrun1': {'hitWidth': 125, 'hitHeight': 125},
  'boyrun2': {'hitWidth': 125, 'hitHeight': 125},
  'boyrun3': {'hitWidth': 125, 'hitHeight': 125},
  'boyrun4': {'hitWidth': 125, 'hitHeight': 125},
  'boyjump1': {'hitWidth': 125, 'hitHeight': 125},
  'boyjump2': {'hitWidth': 125, 'hitHeight': 125},
  'boyjump3': {'hitWidth': 125, 'hitHeight': 125},
  'boyfall1': {'hitWidth': 125, 'hitHeight': 125},
  'boyfall2': {'hitWidth': 125, 'hitHeight': 125},
  'boyfall3': {'hitWidth': 125, 'hitHeight': 125},
  'boyfall4': {'hitWidth': 125, 'hitHeight': 125},
  'boyfall5': {'hitWidth': 125, 'hitHeight': 125},
  'seamonster': {'hitWidth': 300, 'hitHeight': 100},
  'navalmine': {'hitWidth': 200},
  'pebble': {'hitWidth': 25,'hitHeight': 25},
  'icespike': {'hitWidth': 30},
  'penguin3': {'hitWidth': 200, 'hitHeight': 50},
  'reef': {'hitWidth': 325, 'hitHeight': 200},
  'doghappy': {'width': 700, 'height': 700},
  'scope': {'width': 200, 'height': 200},
  'shot': {'width': 200, 'height': 200},
  'bone2': {'width': 200, 'height': 200},
  'chalk': {'thumbBackground': '#808080'},
  'quill2': {'thumbBackground': '#808080'},
  'coin': {'loops': 999},
  'fire': {'loops': 999},
  '2mustangs': {'hideInAssetsPanel': true},
  'annabanana': {'hideInAssetsPanel': true},
  'evanhavingfun': {'hideInAssetsPanel': true},
  'fracturedplanet': {'hideInAssetsPanel': true},
  'happyallie': {'hideInAssetsPanel': true},
  'happydevan': {'hideInAssetsPanel': true},
  'happyelena': {'hideInAssetsPanel': true},
  'happynolan': {'hideInAssetsPanel': true},
  'jacker': {'hideInAssetsPanel': true},
  'jamesbombed': {'hideInAssetsPanel': true},
  'jeffreyfootball': {'hideInAssetsPanel': true},
  'rinniebinnie': {'hideInAssetsPanel': true},
  'ruinsinathens': {'hideInAssetsPanel': true},
  'shadowedyellowcube': {'hideInAssetsPanel': true},
  'smilingallie': {'hideInAssetsPanel': true},
  'smilingjack': {'hideInAssetsPanel': true},
  'smilingnature': {'hideInAssetsPanel': true},
  'annafrozen': {'hideInAssetsPanel': true},
  'brendanwithparrot': {'hideInAssetsPanel': true},
  'brotherwake': {'hideInAssetsPanel': true},
  'calliethedog': {'hideInAssetsPanel': true},
  'cameronandclark': {'hideInAssetsPanel': true},
  'claireinhawaii': {'hideInAssetsPanel': true},
  'curtseychibi': {'hideInAssetsPanel': true},
  'darkangel': {'hideInAssetsPanel': true},
  'flyingsidekick': {'hideInAssetsPanel': true},
  'garrettgreenshirt': {'hideInAssetsPanel': true},
  'garretthead': {'hideInAssetsPanel': true},
  'gavinandfriend': {'hideInAssetsPanel': true},
  'gavinfishing': {'hideInAssetsPanel': true},
  'gavinwithbaby': {'hideInAssetsPanel': true},
  'happybrady': {'hideInAssetsPanel': true},
  'happymaribella': {'hideInAssetsPanel': true},
  'happynathan': {'hideInAssetsPanel': true},
  'hayboys': {'hideInAssetsPanel': true},
  'hinatahyuganaruto': {'hideInAssetsPanel': true},
  'ionaswimming': {'hideInAssetsPanel': true},
  'islariding': {'hideInAssetsPanel': true},
  'lahti': {'hideInAssetsPanel': true},
  'lani': {'hideInAssetsPanel': true},
  'misspiggy': {'hideInAssetsPanel': true},
  'misspiggy2': {'hideInAssetsPanel': true},
  'prettymangagirl': {'hideInAssetsPanel': true},
  'reba': {'hideInAssetsPanel': true},
  'samandcousin': {'hideInAssetsPanel': true},
  'samandfamily': {'hideInAssetsPanel': true},
  'samrugby': {'hideInAssetsPanel': true},
  'samrugby2': {'hideInAssetsPanel': true},
  'sillysisters': {'hideInAssetsPanel': true},
  'sirdaddy': {'hideInAssetsPanel': true},
  'sistertori': {'hideInAssetsPanel': true},
  'skyebiking': {'hideInAssetsPanel': true},
  'smilingboys': {'hideInAssetsPanel': true},
  'totoro': {'hideInAssetsPanel': true},
  'unicorn2': {'hideInAssetsPanel': true},
  'wizard': {'hideInAssetsPanel': true},
  'archerben': {'hideInAssetsPanel': true},
  'anthonywithcar': {'hideInAssetsPanel': true},
  'bobby': {'hideInAssetsPanel': true},
  'bobby2': {'hideInAssetsPanel': true},
  'bobbyblue': {'hideInAssetsPanel': true},
  'bobbypink': {'hideInAssetsPanel': true},
  'trophy': {'hideInAssetsPanel': true},
  'prize': {'hideInAssetsPanel': true},
  'adventurekitty': {'hideInAssetsPanel': true},
  'diykitty': {'hideInAssetsPanel': true},
  'mariachikitty': {'hideInAssetsPanel': true},
  'gearssoi': {'hideInAssetsPanel': true},
  'logosoi': {'hideInAssetsPanel': true},
  'smilinglauren': {'hideInAssetsPanel': true},
  'kidrobotmunny': {'hideInAssetsPanel': true},
  'munnylogos': {'hideInAssetsPanel': true},
  'baritone': {'thumbBackground': '#808080'},
  'beam': {'thumbBackground': '#808080'},
  'bird4': {'thumbBackground': '#808080'},
  'bite': {'thumbBackground': '#808080'},
  'cow3': {'thumbBackground': '#808080'},
  'eye': {'thumbBackground': '#808080'},
  'flare': {'thumbBackground': '#808080'},
  'glasses': {'thumbBackground': '#808080'},
  'hud': {'thumbBackground': '#808080'},
  'iconreflection': {'thumbBackground': '#808080'},
  'lander': {'thumbBackground': '#808080'},
  'laser': {'thumbBackground': '#808080'},
  'lightning': {'thumbBackground': '#808080'},
  'maraca': {'thumbBackground': '#808080'},
  'maracas': {'thumbBackground': '#808080'},
  'pandakid': {'thumbBackground': '#808080'},
  'plunger': {'thumbBackground': '#808080'},
  'rayshot': {'thumbBackground': '#808080'},
  'rocket3': {'thumbBackground': '#808080'},
  'snowflake': {'thumbBackground': '#808080'},
  'soccernet': {'thumbBackground': '#808080'},
  'spacemandoll': {'thumbBackground': '#808080'},
  'tooth': {'thumbBackground': '#808080'},
  'trumpet': {'thumbBackground': '#808080'},
  'whitebox': {'thumbBackground': '#808080'},
  '_unit_test_do_not_delete': {'loops': 5, 'hideInAssetsPanel': true},
  'coatofarms': {'hideInAssetsPanel': true},
  'schoolrye': {'hideInAssetsPanel': true},
  'celina': {'hideInAssetsPanel': true},
  'corban': {'hideInAssetsPanel': true},
  'dick': {'hideInAssetsPanel': true},
  'booby': {'hideInAssetsPanel': true},
  'marshmellow': {'hideInAssetsPanel': true},
  'rock200x200': {'hideInAssetsPanel': true},
  'scarlsen': {'hideInAssetsPanel': true},
  'scarlsen2': {'hideInAssetsPanel': true},
  'scarlsen3': {'hideInAssetsPanel': true},
  'scarlsen4': {'hideInAssetsPanel': true},
  'scarlsen5': {'hideInAssetsPanel': true},
  'scarlsen6': {'hideInAssetsPanel': true},
  'scarlsen7': {'hideInAssetsPanel': true},
  'scarlsen8': {'hideInAssetsPanel': true}
};
